apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage-python-app.fullname" . }}
  labels:
    {{- include "backstage-python-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.targetPort.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "backstage-python-app.selectorLabels" . | nindent 4 }}
